### ISSUE TITLE
snmpsim and snmp_exporter (prometheus)

### ISSUE THREAD

**Issue by JeGoi** [etingof/snmpsim#127]
What is the best way to use snmpsim as an snmp simulator for snmp_exporter (prometheus) on the same server test (prometheus/snmp-exporter, snmpsim) ?
Any advice ?

http://snmplabs.com/snmpsim/changelog.html#revision-1-0-0-released-xx-12-2019
"Future modules may just send out the information to external collectors e.g. Graphite/Carbon or store it in some other format e.g. Prometheus."
Any developments on it?

Thank you

**Comment by etingof** [comment]
> What is the best way to use snmpsim as an snmp simulator for snmp_exporter (prometheus) on the same server test (prometheus/snmp-exporter, snmpsim) ?

I do not see much difference in where the server is located. Why this can be important if the network is operational?

> http://snmplabs.com/snmpsim/changelog.html#revision-1-0-0-released-xx-12-2019
> "Future modules may just send out the information to external collectors e.g. Graphite/Carbon or store it in some other format e.g. Prometheus."
> Any developments on it?

So far only JSON file can be written with snmpsim stats inside. It is almost trivial to add another module to forward this information elsewhere (e.g. Prometheus).

However I am not sure I understand your goal correctly. What exactly you want to monitor?

**Comment by JeGoi** [comment]
Hum, I'm not sure it is finally a snmpsim problem.
I've run snmpsim on multiple localhost 127.0.0.1 to 127.0.0.5 (http://snmplabs.com/snmpsim/documentation/tips-and-tricks.html#multiple-instances) with a modification of iptable to redirect port 161 to 1161.
With snmpwalk a runner on 127.0.0.10, for example, fails.
With snmpexporter a local ip address (no matter which one) is always return a results.
I will close this issue because I'm not sure it is a snmpsim issue a iptable or snmp-exporter issue.
