### ISSUE TITLE
Abilty for record strings as Plain text.

### ISSUE THREAD

**Issue by landy2005** [etingof/snmpsim#13]
I have old and new versions of snmprec:

Old version record string values as plain text.
`snmprec --agent-udpv4-endpoint=x.x.x.x --start-oid=1.3.6.1.2.1 --stop-oid=1.3.6.1.2.1.1 --output-file=aix.snmprec`

old (0.2.4):
```
1.3.6.1.2.1.1.1.0|4|AIX su0506 3 5 00C6E81B4C00
1.3.6.1.2.1.1.2.0|6|1.3.6.1.4.1.8072.3.2.15
1.3.6.1.2.1.1.3.0|67|1399875231
1.3.6.1.2.1.1.4.0|4|postmaster@rwe-services.cz
1.3.6.1.2.1.1.5.0|4|su0506
1.3.6.1.2.1.1.6.0|4|CDC Brno
```
new (0.3.1):
```
1.3.6.1.2.1.1.1.0|4x|414958207375303530362033203520303043364538314234433030
1.3.6.1.2.1.1.2.0|6|1.3.6.1.4.1.8072.3.2.15
1.3.6.1.2.1.1.3.0|67|1399644038
1.3.6.1.2.1.1.4.0|4x|706f73746d6173746572407277652d73657276696365732e637a
1.3.6.1.2.1.1.5.0|4|su0506
1.3.6.1.2.1.1.6.0|4x|4344432042726e6f
```

For devel purposes I prefer to use Plain strings (4) instead hex (4x).

**Please add ability (command line argument) for force decode hex strings to plain in snmprec command.**

**Comment by etingof** [comment]
Just a quick note that I'm working on the feature you've proposed. The idea is to escape non-printables while leaving ASCII as-is.

**Comment by landy2005** [comment]
Nice, will wait this.
Thanks!

**Comment by 0x003e** [comment]
@landy2005 SFR ?

**Comment by landy2005** [comment]
@0x003e what?

**Comment by etingof** [comment]
It's me to blame. Sorry, I started working on [the feature](https://github.com/etingof/snmpsim/tree/readable-strings-encoding) discussed here, but got distracted and have not finished it yet.

But I promise to get it done. ;-)

**Comment by etingof** [comment]
@landy2005 You are welcome to test [this implementation](https://github.com/etingof/snmpsim/pull/24). Let me know if it is LGTM so I could merge & release.

**Comment by landy2005** [comment]
Seems as fine for _datafile.py_ conversion.

But for _snmprec.py_ I think should used this logic:
STRING store as 4 or 4e (if escape chars exist)
HEX-STRING always store as 4x format.

What I mean.. currently _datafile.py --escaped-strings_ convert all hex strings into escaped (also if this oid really hex string).. such entries less readable as escaped than as hex :)

diff example for conversion
```
< 1.3.6.1.4.1.2636.3.18.2.2.0|4e|\x07\xe1\x0b\x11\x0f\x06\x05\x00+\x01\x00
---
> 1.3.6.1.4.1.2636.3.18.2.2.0|4x|07e10b110f0605002b0100

< 1.3.6.1.4.1.2636.3.36.1.1.1.0|4e|\nK\x01\x05
---
> 1.3.6.1.4.1.2636.3.36.1.1.1.0|4x|0a4b0105
```

**Comment by etingof** [comment]
I am not sure I understand your point. How do you define HEX-STRING? Mind you, escapes only happen for non-printables.

Here are the cases we presently deal with:

* fully printable ascii always remains as such
* string with a non-printable char(s):

  - default mode: fully hexified
  - escaped mode:  non-printables are hex-escape, printable remain as-is

WDIT?

**Comment by landy2005** [comment]
yah, forget it, I was wrong.

But my "idea" if 90-100% of string is non-printable (as in my diff example) - use 4x..

**Comment by etingof** [comment]
Merged. Thank you!
