### ISSUE TITLE
snmp simulator

### ISSUE THREAD

**Issue by shmn18** [etingof/snmpsim#157]
$ snmpsim-command-responder --data-dir=./Desktop/snmprec --agent-udpv4-endpoint=127.0.0.1:1024

I have the simulation data on the desktop in a folder named snmprec. When I run the command I get the error as command not found. I'm using ubuntu 18.04. Can anyone help me in this? 

Thank you

**Comment by gainskills** [comment]
> $ snmpsim-command-responder --data-dir=./Desktop/snmprec --agent-udpv4-endpoint=127.0.0.1:1024
> 
> I have the simulation data on the desktop in a folder named snmprec. When I run the command I get the error as command not found. I'm using ubuntu 18.04. Can anyone help me in this?
> 
> Thank you

the command depends on the Python environment, or can you try with venv ?

**Comment by shmn18** [comment]
Thank you. Its solved now.
