### ISSUE TITLE
No mib2dev from Free SNMP simulator in ubuntu 16.4

### ISSUE THREAD

**Issue by GeorgePapageorgakis** [etingof/snmpsim#16]
I have installed free SNMP simulator and I followed the installation instructions: https://github.com/etingof/snmpsim and everything seemed to be ok.

However, when I tried to `mib2dev` tool I get `command not found`.
When I tried to find if it exists i get:
```
    ~$ sudo find -name "mib2dev"
    ./.local/snmpsim/data/mib2dev
```
but still no `mib2dev.py` anywhere.
```
    ~/.local/snmpsim/data/mib2dev$ ls -a
    host-resources-mib.snmprec  ip-mib.snmprec  tcp-mib.snmprec  udp-mib.snmprec
```

I even tried reinstalling but nothing changed.
Any help would be appreciated.

**Comment by etingof** [comment]
The `mib2dev` tool is no different from the others shipped with snmpsim. How exactly you install it? 

The most common way would be to set up a virtual environment and pip install snmpsim into it:

    $ python3 -m venv venv
    $ source venv/bin/activate
    (venv) $ pip install snmpsim
    (venv) $ which mib2dev.py
    ~/snmpsim/venv/bin/mib2dev.py

**Comment by GeorgePapageorgakis** [comment]
As the instructions say:
Just run:
$ pip install snmpsim
and it was installed. 
Should I uninstall it and install it with a different method?

**Comment by GeorgePapageorgakis** [comment]
I installed as you suggested and seems to be ok only within the venv.
