### ISSUE TITLE
what is the command to convert .mib to file format for simulator?

### ISSUE THREAD

**Issue by lovelyplanet2019** [etingof/snmpsim#178]
what is the command to convert TmrSys1Data.mib to file format for simulator?

**Comment by lextm** [comment]
You should spend enough time on the documentation, as such has been well documented,

https://docs.lextudio.com/snmpsim/quick-start#simulate-from-mib

**Comment by lovelyplanet2019** [comment]
> You should spend enough time on the documentation, as such has been well documented,
> 
> https://docs.lextudio.com/snmpsim/quick-start#simulate-from-mib

thanks. i wasn't aware of this documentation.
I am in Windwos cmd. and this command does not works. 
pipenv run snmpsim-command-responder

I saw some .py files installed at here C:\Program Files\Python311\Scripts 
should i call them individually? filename.py follow by command....

**Comment by lovelyplanet2019** [comment]
Error:
C:\Windows\system32>pipenv run snmpsim-command-responder --data-dir=./data
Creating a virtualenv for this project...
Pipfile: C:\Windows\System32\Pipfile
Using default python from C:\Program Files\Python311\python.exe (3.11.4) to create virtualenv...
[  ==] Creating virtual environment...created virtual environment CPython3.11.4.final.0-64 in 6018ms
  creator CPython3Windows(dest=C:\Users\gan\.virtualenvs\System32-eU24dAeB, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\a\AppData\Local\pypa\virtualenv)
    added seed packages: pip==24.0, setuptools==69.5.1, wheel==0.43.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\a\.virtualenvs\System32-eU24dAeB
Creating a Pipfile for this project...
'snmpsim-command-responder' is not recognized as an internal or external command,
operable program or batch file.

**Comment by lovelyplanet2019** [comment]
ok it seems works after correcting python env
