### ISSUE TITLE
Installation problem in windows7

### ISSUE THREAD

**Issue by vijayiiit137** [etingof/snmpsim#18]
Iam using latest version of vxsnmpsimulator-2.0.1 . I am following steps that you mentioned in readme file.
But it is throwing me error like as follows
Error: Could not find or load main class Files\Java\jdk1.8.0_60\bin\JAVA  -jar j
ar\SnmpAgentSimulator-jetty-console.war --headless --contextPath .SnmpAgentSimul
ator --port 8080
 I checked java path also(i reinstalled also).
Iam thinking that is due to any port issues. please help me in this.
Thanks in advance.

**Comment by etingof** [comment]
Looks like you are using [Verax SNMP simulator](http://www.veraxsystems.com/en/products/free-snmp-agent-simulator) while this project is about the [Free SNMP Simulator](http://snmpsim.sourceforge.net/).

**Comment by vijayiiit137** [comment]
Ho,ok tq. Can you help me where to raise this issue. I am not able to find in google
