### ISSUE TITLE
AttributeError: module 'snmpsim.log' has no attribute 'gMap'

### ISSUE THREAD

**Issue by paddor** [etingof/snmpsim#180]
Starting snmpsimd with `snmpsimd --data-dir=bin/snmp-data/ --v2c-arch --agent-udpv4-endpoint=127.0.0.1:1161`, I get:

```
Traceback (most recent call last):
  File "/usr/bin/snmpsimd", line 576, in <module>
    '|'.join(log.gMap),
AttributeError: module 'snmpsim.log' has no attribute 'gMap'
```

Starting it with `--help` shows the same error.

**Comment by lextm** [comment]
How did you install snmpsim on this machine? It's likely to be a package corruption.

There is nothing like `log.gMap` in the code base neither, and the closest is `flagMap`. Since the name `snmpsimd` isn't exclusive to this repo, you need to check if you are using something else.

**Comment by paddor** [comment]
I installed version 0.4.5-1 with `sudo apt install snmpsim` on Ubuntu 22.04. A reinstall did not help.

The executable `/usr/bin/snmpsimd` contains these lines:
```
 571     [--agent-unix-endpoint=</path/to/named/pipe>]""" % (
 572         sys.argv[0],
 573         '|'.join([x for x in getattr(pysnmp_debug, 'FLAG_MAP', getattr(pysnmp_debug, 'flagMap', ()))
 574                   if x != 'mibview']),
 575         '|'.join([x for x in getattr(pyasn1_debug, 'FLAG_MAP', getattr(pyasn1_debug, 'flagMap', ()))]),
 576         '|'.join(log.gMap),
 577         '|'.join(sorted([x for x in authProtocols if x != 'NONE'])),
 578         '|'.join(sorted([x for x in privProtocols if x != 'NONE']))
 579     )
```

On line 576 it says `log.gMap`.

**Comment by lextm** [comment]
> I installed version 0.4.5-1 with `sudo apt install snmpsim` on Ubuntu 22.04.

That's a very important hint and the relevant code can be found from a very old release from 2018, 

https://github.com/etingof/snmpsim/blob/v0.4.5/scripts/snmpsimd.py#L576

However, `apt install` indicates the version you use was packed by someone as Ubuntu package. The packaging process might change the functionality, and not covered by this repo or any fork from it.

If possible, uninstall this Ubuntu package and switch to the normal Python package from PyPI, and note that you should use a more recent release (such as 0.4.8 from this repo, or 1.1.0 from LeXtudio Inc.).

**Comment by paddor** [comment]
Thank you. With version 0.4.7 installed via `pip install snmpsim`  it works.
