### ISSUE TITLE
Configure community for SQL variation module?

### ISSUE THREAD

**Issue by scottharman** [etingof/snmpsim#182]
Hi team - ideally I'd like to map different tables to different simulated endpoints from an sqlite database, but I'm not clear on whether this actually exists or whether I ned to create this?

My specific use case is simulating a number of devices from the same vendor, and I've got snmprec files for each of these, but ideally I would like to have them in a database and use the SQL variation module so I can treat them as 'live' devices to manipulate.

I've got an sqlite database that I have previously populated, but can't see how I associate the individual tables with community names or endpoints.  Is anyone able to point me in the right direction?
Ideally I would explicitly associate each table with a community, that way the general properties are reported back correctly for each unit.

**Comment by lextm** [comment]
Please read etingof/pysnmp#429 first.
