### ISSUE TITLE
couldn't create a lot for simulator.

### ISSUE THREAD

**Issue by mslee89** [etingof/snmpsim#2]
hi.

i can created 1013 simulator.
but i will should create 2026 simulator.
And it was experiencing the following error.

[root@seob ~]# cat ips.txt  | wc -l
2026

```
[root@seob ~]# snmpsimd.py --args-from-file=/root/ips.txt --data-dir=/usr/lib/python2.7/site-packages/snmpsim-0.3.0-py2.7.egg/snmpsim/data --v2c-arch --process-user=root --process-group=root --daemonize --pid-file=/root/snmpsimd.pid
ERROR: socket() failed: [Errno 24] Too many open files
```

can simulator create a lot ?

**Comment by v-zhuravlev** [comment]
You need to increase the number of files allowed to be opened simultaneously in your system. By default it is limited to 1024. Search around the web how to do it.

**Comment by etingof** [comment]
You need to run `ulimit -n 2030` in your shell prior to invoking snmpsimd from the same shell. That will raise file descriptors limit for your shell and its child processes to 2030 open descriptors.

**Comment by mslee89** [comment]
@v-zhuravlev @etingof thank you for the answer.
