### ISSUE TITLE
Tag above 9 is not accepted

### ISSUE THREAD

**Issue by guy032** [etingof/snmpsim#28]
data error at ./data2\192.168.0.68.snmprec controller for 1.3.6.1.2.1.1.2.0: value evaluation error for tag '67', value '4 days, 15:06:46.85'

**Comment by etingof** [comment]
But that is correct -- tag 67 stands for SNMP TimeTicks type. Values should be integers like this:

    1.3.6.1.2.1.1.3.0|67|233425120
