### ISSUE TITLE
There is no CPU data?

### ISSUE THREAD

**Issue by axiaoxin** [etingof/snmpsim#31]
I can't find the CPU info in the public community

    $ snmpwalk -v 2c -c public 127.0.0.1| grep -i cpu
    $

**Comment by etingof** [comment]
Well, it's all in your hands! ;-)

Just pick a MIB which exports the information you need (CPU reading) and add those OIDs-values to your [.snmprec file](http://snmplabs.com/snmpsim/simulating-agents.html#simulation-data).
