### ISSUE TITLE
ERROR: pylibpcap package is missing!

### ISSUE THREAD

**Issue by ChristopheVidaillac** [etingof/snmpsim#33]
I tried to use pcap2dev.py tool against an tcpdump file and got the issue:

[root@mimicsnmp ~]# pcap2dev.py --output-dir=/opt/SNMP_repo/tcpdumps --capture-file=net_trace_63.218.170.5.tc                                pdump
ERROR: pylibpcap package is missing!
Get it from http://sourceforge.net/projects/pylibpcap/
Usage: /usr/bin/pcap2dev.py [--help]
    [--version]
....

I'm running a python version 2.7 and understood that I need to install the pylibpcap package but got the following issue when I tried to install that package:

[root@mimicsnmp ~]# pip install pylibpcap -vvv
Collecting pylibpcap
  1 location(s) to search for versions of pylibpcap:
  * https://pypi.python.org/simple/pylibpcap/
  Getting page https://pypi.python.org/simple/pylibpcap/
  Looking up "https://pypi.python.org/simple/pylibpcap/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/pylibpcap/ HTTP/1.1" 200 93
  Updating cache with response from "https://pypi.python.org/simple/pylibpcap/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/pylibpcap/
  Could not find a version that satisfies the requirement pylibpcap (from versions: )
Cleaning up...
No matching distribution found for pylibpcap
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for pylibpcap
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
Current age based on date: 5465272
Freshness lifetime from max-age: 600
The cached response is "stale" with no etag, purging
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 72983
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching b/c date exists and max-age > 0

Any idea to help me to make it running this great tool on my Redhat :-) ?

Thanks for your help

Christophe

**Comment by etingof** [comment]
I think this has something to do with the `pylibpcap` module at PyPI. I got this feeling that this wrapper around `pcap` is dead. So may be we should migrate to `pcapy` or something else.

Meanwhile I think I've managed to pull `pylibpcap` from SourceForge by direct download link:

```
$ pip install https://downloads.sourceforge.net/project/pylibpcap/pylibpcap/0.6.4/pylibpcap-0.6.4.tar.gz
Collecting https://downloads.sourceforge.net/project/pylibpcap/pylibpcap/0.6.4/pylibpcap-0.6.4.tar.gz
  Downloading https://downloads.sourceforge.net/project/pylibpcap/pylibpcap/0.6.4/pylibpcap-0.6.4.tar.gz (49kB)
    100% |################################| 51kB 364kB/s 
Building wheels for collected packages: pylibpcap
...
```

Let's see if that helps?

**Comment by ChristopheVidaillac** [comment]
Thanks for your reply. I did the sa

**Comment by ChristopheVidaillac** [comment]
Hello, 
I found the problem for the "fatal error: pcap.h: No such file or directory".
I ran in Redhat 7.X and no libpcap-devel package available. So, I was obliged to get the 2 following packages from WWW and install in my Redhat7.x

libpcap-1.5.3-8.el7.i686
libpcap-devel-1.5.3-9.el7.x86_64

After that, I was able to install pylibpcap-0.6.4 package successfully. Just got some warnings during compulation:

[root@mimicsnmp pylibpcap-0.6.4]# !./setup.py
./setup.py install
running install
running build
running build_ext
building '_pcapmodule' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DSWIG_COBJECT_TYPES -I/usr/include/python2.7 -c pcap.c -o build/temp.linux-x86_64-2.7/pcap.o
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DSWIG_COBJECT_TYPES -I/usr/include/python2.7 -c pcap_interface.c -o build/temp.linux-x86_64-2.7/pcap_interface.o
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DSWIG_COBJECT_TYPES -I/usr/include/python2.7 -c exception.c -o build/temp.linux-x86_64-2.7/exception.o
In file included from /usr/include/python2.7/pyconfig.h:6:0,
                 from /usr/include/python2.7/Python.h:8,
                 from exception.c:19:
/usr/include/python2.7/pyconfig-64.h:1188:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/include/stdlib.h:24:0,
                 from exception.c:17:
/usr/include/features.h:168:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/include/python2.7/pyconfig.h:6:0,
                 from /usr/include/python2.7/Python.h:8,
                 from exception.c:19:
/usr/include/python2.7/pyconfig-64.h:1210:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
 #define _XOPEN_SOURCE 600
 ^
In file included from /usr/include/stdlib.h:24:0,
                 from exception.c:17:
/usr/include/features.h:170:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
 ^
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DSWIG_COBJECT_TYPES -I/usr/include/python2.7 -c error.c -o build/temp.linux-x86_64-2.7/error.o
In file included from /usr/include/python2.7/pyconfig.h:6:0,
                 from /usr/include/python2.7/Python.h:8,
                 from error.c:18:
/usr/include/python2.7/pyconfig-64.h:1188:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/include/sys/types.h:25:0,
                 from /usr/include/pcap/pcap.h:46,
                 from /usr/include/pcap.h:45,
                 from error.c:17:
/usr/include/features.h:168:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/include/python2.7/pyconfig.h:6:0,
                 from /usr/include/python2.7/Python.h:8,
                 from error.c:18:
/usr/include/python2.7/pyconfig-64.h:1210:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
 #define _XOPEN_SOURCE 600
 ^
In file included from /usr/include/sys/types.h:25:0,
                 from /usr/include/pcap/pcap.h:46,
                 from /usr/include/pcap.h:45,
                 from error.c:17:
/usr/include/features.h:170:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
 ^
creating build/lib.linux-x86_64-2.7
gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/pcap.o build/temp.linux-x86_64-2.7/pcap_interface.o build/temp.linux-x86_64-2.7/exception.o build/temp.linux-x86_64-2.7/error.o -L/usr/lib64 -lpcap -lpython2.7 -o build/lib.linux-x86_64-2.7/_pcapmodule.so
running build_py
copying pcap.py -> build/lib.linux-x86_64-2.7
running install_lib
copying build/lib.linux-x86_64-2.7/_pcapmodule.so -> /usr/lib64/python2.7/site-packages
copying build/lib.linux-x86_64-2.7/pcap.py -> /usr/lib64/python2.7/site-packages
byte-compiling /usr/lib64/python2.7/site-packages/pcap.py to pcap.pyc
running install_egg_info
Writing /usr/lib64/python2.7/site-packages/pylibpcap-0.6.4-py2.7.egg-info
[root@mimicsnmp pylibpcap-0.6.4]#


So, now
