### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by murrant** [etingof/snmpsim#35]
Hi @etingof 

Thanks for snmpsim, we are using it at https://github.com/librenms/librenms to test our software.

I was wondering if you had any tips or perhaps code improvements to speed up our tests run time.  We've only just started adding data to automated tests and the time is starting to add up.  Our unit tests are up to almost 9 minutes.

**Comment by etingof** [comment]
Hey, I am glad the tools is useful! ;-)

Do you run your tests in parallel? That would throttle a single instance of snmpsim so you could just add some more.

Of is it that you run long walks?

What is the load profile you put on it?

**Comment by murrant** [comment]
phpunit is single threaded without external tools.  We run our test on Travis CI, so I'm not sure about loads.

When I run locally on my dev computer, it seems to be disk IO bound, not CPU bound.

Lots of snmprec files, I'd say moderate walks.

**Comment by etingof** [comment]
How about trying to put .snmprec files (and their indices) on a ramdisk file system like tmpfs?

**Comment by etingof** [comment]
The `snmpsimd` process does not keep [more than 32 .snmprec files](https://github.com/etingof/snmpsim/blob/master/scripts/snmpsimd.py#L229) at once. If you have enough RAM you can try to bump up this variable. I'd be interested to know if it helps.

**Comment by murrant** [comment]
Just to give you an idea our test data is 723 snmprec files, but only 4.5MB.

I bumped `maxQueueEntries` up to 300, then 800.  It didn't seem to make a difference.

A ramdisk only bought me about 1m I'm going to try setting up parallel testing and see what that does.

Thanks for your input.

**Comment by etingof** [comment]
BTW, if you can do GETBULK instead of GETNEXT walks, that would boost the performance. But I do now know is that fits your test cases.

Even with ramdisk, is it still I/O bound? Do you do snmpsim logging? Writing significant traffic in log may throttle disk I/O a bit...

**Comment by murrant** [comment]
Found out we had some unexpected waits in the tests.  Now we are clearly cpu bound, snmpsim is the minority user.  I see you are working on a v2 only responder, can't wait for that ;)
