### ISSUE TITLE
Unable to request the UDP Port

### ISSUE THREAD

**Issue by SanthoshASG** [etingof/snmpsim#39]
My first time with Python - I installed the 64 bit python and pip and also the snmpsim.
With help of this command "snmpsimd.py --data-dir=./data --agent-udpv4-endpoint=10.60.120.121:1025"
I was able to get the below message 
"Listening at UDP/IPv4 endpoint 10.60.120.121:1025, transport ID 1.3.6.1.6.1.1.0"
Means I am able to start a UDP port on my local ip.

However when I try to execute the below command 
"snmprec.py --agent-udpv4-endpoint=10.60.120.121:1025 --output-file=C:/Users/Santhoshkumar.Sekar/AppData/Local/Programs/Python/Python36/snmpsim/data/public.snmprec"
I get this error,
"SNMP Engine error: No SNMP response received before timeout"

Also attached the full logs. Please check and let me know.

Regards,
Santhosh
[snmpsim.txt](https://github.com/etingof/snmpsim/files/2068522/snmpsim.txt)
[snmprec.txt](https://github.com/etingof/snmpsim/files/2068524/snmprec.txt)

**Comment by etingof** [comment]
I can think of two potential problems to check out here:

* In the snmpsimd log there is no mention of any .snmprec files picked up on load. That means that snmpsimd has nothing to respond with
* Once you have your simulation data e.g. *.snmprec* files in place, make sure that you pass one of their names as SNMP community name to the *snmprec* tool
* Make sure your local firewall does allow UDP/1025 traffic
