### ISSUE TITLE
model different devices

### ISSUE THREAD

**Issue by infotek** [etingof/snmpsim#4]
It would be great to host models devices.  For example, I wrote a nagios check for dell openmanage devices.  After changing companies, to one that did not use Dell, I was unable to continue development.

**Comment by etingof** [comment]
If you have models to share, you are more than welcome to send them to me (PR or e-mail) so I can configure them to [public simulator instance](http://snmpsim.sourceforge.net/public-snmp-simulator.html) at `demo.snmplabs.com`.

**Comment by etingof** [comment]
Quick update: if you do
```
snmpwalk -v2c -c public demo.snmplabs.com 1.3.6
```
you will now get a way more realistic simulation of a live Linux host.
