### ISSUE TITLE
Attaching to default SNMP port

### ISSUE THREAD

**Issue by RenanMuratori** [etingof/snmpsim#50]
I would like the simulator to answer get requisitions on the default SNMP port (port 161).
Is that possible?

**Comment by etingof** [comment]
Most certainly! Just use `--agent-udpv4-endpoint=0.0.0.0:161` for that.

**Comment by RenanMuratori** [comment]
Hi etingof, thanks for the answer.

I tried your sugestion but it didnt work, i got the following error when trying to execute the simulator with my own user and then root:

[my_user]$ snmpsimd.py --data-dir=./snmpsim_data --agent-udpv4-endpoint=0.0.0.0:161
ERROR: bind() for ('0.0.0.0', 161) failed: [Errno 13] Permission deniedcaused by <class 'socket.error'>: [Errno 13] Permission denied

[root]# snmpsimd.py --data-dir=./snmpsim_data --agent-udpv4-endpoint=0.0.0.0:161
ERROR: cant drop priveleges: Must drop priveleges to a non-priveleged user&group

My user doesnt have permissison to use port 161, but when i try it using root, i get the message saying that it must drop privileges. I´ve tried this using "sudo" on my user, but i get the same permission denied message.

**Comment by etingof** [comment]
That's right, you should add the `--process-user=nobody` and `--process-group=nogroup` options. Of course, the dedicated non-privileged user and group can be different.

**Comment by RenanMuratori** [comment]
It works!!

Thank you for the help @etingof !!
