### ISSUE TITLE
snmpbulkget doesn't seem to be supported

### ISSUE THREAD

**Issue by murrant** [etingof/snmpsim#6]
```
$ snmpbulkget -v2c -c unit_tests 127.0.0.1:11161 sysDescr.0 sysName.0
Timeout: No Response from 127.0.0.1:11161
$ snmpget -v2c -c unit_tests 127.0.0.1:11161 sysDescr.0 sysName.0
SNMPv2-MIB::sysDescr.0 = STRING: Unit Tests sysDescr
SNMPv2-MIB::sysName.0 = STRING: Unit Tests sysName
```

Did I miss something?

**Comment by etingof** [comment]
`snmpbulkget` uses SNMP GETBULK command which is supported my snmpsim.

Could you please run snmpsimd with `--debug=secmod,io,dip,msgproc` option and let us see what is on the output?

**Comment by murrant** [comment]
Here is the full log output: https://gist.github.com/62ddde0b48ee36c8785028bb170605b6

The relevant bit seems to be:
```
generateResponseMsg: serialization failure: Short OID 
StatusInformation: {'errorIndication': <pysnmp.proto.errind.SerializationError object at 0x7f7945041160>}
```

**Comment by murrant** [comment]
Hmm, seems to be an issue with the snmprec file.  I added a more complete snmprec file and it seems to work better.

**Comment by etingof** [comment]
The serialization error you spotted might be due to malformed OID value in response:

    variable-bindings=VarBindList:
        VarBind:
         name=1.3.6.1.2.1.1.2.0
         =_BindValue:
          value=ObjectSyntax:
           simple=SimpleSyntax:
            objectID-value=

Short OID might originate from your .snmprec file. After you fixed it, does the whole thing work as expected?
