### ISSUE TITLE
cache-dir created with wrong ownership when using process-user flag on 0.4.6

### ISSUE THREAD

**Issue by sweatybridge** [etingof/snmpsim#60]
`snmpsimd.py --process-user=nobody --process-group=nogroup --cache-dir=/tmp/snmp-cache`

When running the above command with version 0.4.6, the newly created `snmp-cache` directory is owned by the user executing `snmpsimd.py`. On version 0.4.5 and below, the same command creates the cache directory with ownership assigned to the configurable `process-user` flag, ie. `nobody`.

This seems like a regression after the file permission changes in the new version.

**Comment by etingof** [comment]
Thank you for reporting this! Should be fixed and released shortly.

**Comment by etingof** [comment]
Let's see if commit 8e35fd57d49bab2cee59c154abb23b0bcc67fc8b fixes this problem?
