### ISSUE TITLE
mib2dev.py: nice-to-have: "file not found error message"

### ISSUE THREAD

**Issue by mbonnier-gv** [etingof/snmpsim#64]
It would nice to get a shorter error message when a MIB file is not found.
Something like:" File not found: RFC-1213.py[co]".
Actually we get a difficult to read stack trace.

Thanks for this project,

**Comment by etingof** [comment]
Commit 3e4b2ee90fac8cbce7c1675480a72a74a67fafbc (now in master) should improve this.
