### ISSUE TITLE
snmpset for gauge32 type on snmp v3 ?

### ISSUE THREAD

**Issue by ellos83** [etingof/snmpsim#65]
Hi.

I'm trying to inject Gauge32 data in MIB using snmpget action of snmpsim but I don't know if it is possible, or what's the type I should use.

I've read it is performed used unsigned type (u) but in v3 I think it is not possible (at least it does not work).

How should I proceed.

Thanks a lot,

        Carlos.

**Comment by etingof** [comment]
Are you asking how to simulate `Gauge32` SNMP data type? That [should work](http://snmplabs.com/snmpsim/managing-simulation-data.html#file-format) with all SNMP versions.

**Comment by ellos83** [comment]
You are right, my fault is I was defining it with incorrect type value (65 instead of 66) in snmprec.

Thanks a lot!
