### ISSUE TITLE
snmpsimd.py dies when executing snmpwalk

### ISSUE THREAD

**Issue by kmart5678** [etingof/snmpsim#73]
snmpsimd.py dies after i run the snmpwalk command. Can you help solve this problem?

I followed the steps listed in the quick start guide exactly, but I'm getting following error:

```
  Listening at UDP/IPv4 endpoint 127.0.0.1:1024, transport ID 1.3.6.1.6.1.1.0
Shutting down variation modules:
Variation module "notification" shutdown OK
Variation module "sql" shutdown OK
Variation module "redis" shutdown OK
Variation module "numeric" shutdown OK
Variation module "subprocess" shutdown OK
Variation module "delay" shutdown OK
Variation module "multiplex" shutdown OK
Variation module "error" shutdown OK
Variation module "writecache" shutdown OK
Process terminated
ERROR Traceback (most recent call last):;
ERROR   File "./bin/snmpsimd.py", line 1466, in <module>;
ERROR   File "/root/venv/lib/python2.7/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher;
ERROR PySnmpError: poll error: Traceback (most recent call last):;; 
 File "/root/venv/lib/python2.7/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher;;  
File "/usr/lib64/python2.7/asyncore.py", line 220, in loop;    poll_fun(timeout, map);;  
File "/usr/lib64/python2.7/asyncore.py", line 201, in poll2;    readwrite(obj, flags);; 
 File "/usr/lib64/python2.7/asyncore.py", line 123, in readwrite;    obj.handle_error();;  
File "/usr/lib64/python2.7/asyncore.py", line 108, in readwrite;    obj.handle_read_event();;  
File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event;    self.handle_read();;  
File "/root/venv/lib/python2.7/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 170, in handle_read;;  
File "/root/venv/lib/python2.7/site-packages/pysnmp/carrier/base.py", line 70, in _cbFun;;  
File "/root/venv/lib/python2.7/site-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun;;  
File "/root/venv/lib/python2.7/site-packages/pysnmp/proto/rfc3412.py", line 284, in receiveMessage;;  
File "/root/venv/lib/python2.7/site-packages/pysnmp/smi/builder.py", line 426, in importSymbols;;
MibNotFoundError: No module __SNMPv2-MIB loaded at <pysnmp.smi.builder.MibBuilder object at 0x7f230d363d50>caused by <class 'snmpsim.error.SnmpsimError'>: 
Redis connect parameters not specified;caused by <class 'pysnmp.smi.error.MibNotFoundError'>: 
No module __SNMPv2-MIB loaded at <pysnmp.smi.builder.MibBuilder object at 0x7f230d363d50>caused by <class 'snmpsim.error.SnmpsimError'>:
 Redis connect parameters not specified;
```

Here are the steps i did and env details on linux machine.

```
$ virtualenv venv
$ source venv/bin/activate
$ pip install snmpsim
python ../bin/snmpsimd.py --data-dir=./data --agent-udpv4-endpoint=127.0.0.1:1024 --process-user=<user> --process-group=<group>
```

```
snmpwalk -v2c -c public 127.0.0.1:1024 system
```

Name: Python, Version: 2.7.5
Name: snmpsim,Version: 0.4.7
Name: pysnmp,Version: 4.4.9

**Comment by etingof** [comment]
Do you, by chance, call redis variation module from the .snmprec file invoked for the SNMP query you did?

**Comment by kmart5678** [comment]
> 
> 
> Do you, by chance, call redis variation module from the .snmprec file invoked for the SNMP query you did?

I don't know. I just installed from scratch today and did not modify anything.

**Comment by kmart5678** [comment]
> 
> 
> > Do you, by chance, call redis variation module from the .snmprec file invoked for the SNMP query you did?
> 
> I don't know. I just installed from scratch today and did not modify anything.

(venv) [root@.... venv]# python ./bin/snmpsimd.py --data-dir=./snmpsim/data --agent-udpv4-endpoint=127.0.0.1:1024 --process-user=... --process-group=....
Scanning "/root/.snmpsim/variation" directory for variation modules...
Directory "/root/.snmpsim/variation" does not exist
Scanning "/root/venv/snmpsim/variation" directory for variation modules...
A total of 9 modules found in /root/venv/snmpsim/variation
Scanning "/root/venv/share/snmpsim/variation" directory for variation modules...
Directory "/root/venv/share/snmpsim/variation" does not exist
Scanning "/root/venv/lib/python2.7/site-packages/snmpsim/variation" directory for variation modules...
Directory "/root/venv/lib/python2.7/site-packages/snmpsim/variation" does not exist
Initializing variation modules...
Variation module "notification" from "/root/venv/snmpsim/variation/notification.py" loaded OK
ERROR Variation module "sql" from "/root/venv/snmpsim/variation/sql.py" load FAILED: database type not specified
ERROR Variation module "redis" from "/root/venv/snmpsim/variation/redis.py" load FAILED: Redis connect parameters not specified
Variation module "numeric" from "/root/venv/snmpsim/variation/numeric.py" loaded OK
Variation module "subprocess" from "/root/venv/snmpsim/variation/subprocess.py" loaded OK
Variation module "delay" from "/root/venv/snmpsim/variation/delay.py" loaded OK
Variation module "multiplex" from "/root/venv/snmpsim/variation/multiplex.py" loaded OK
Variation module "error" from "/root/venv/snmpsim/variation/error.py" loaded OK
Variation module "writecache" from "/root/venv/snmpsim/variation/writecache.py" loaded OK
--- SNMP Engine configuration
SNMPv3 EngineID: 0x80004fb8056e6a62626f656d7364613776249c5cb0
  --- Data directories configuration
  SNMPv3 Context Engine ID: 0x80004fb8056e6a62626f656d7364613776249c5cb0
  Scanning "./snmpsim/data" directory for  *.snmpwalk, *.MVC, *.sapwalk, *.snmprec, *.dump data files...
    Configuring /root/venv/snmpsim/data/recorded/linksys-system.snmprec controller
    SNMPv1/2c community name: recorded/linksys-system
    SNMPv3 Context Name: 1a764f7fd0e7b0bf98bada8fe723e488 or recorded/linksys-system
    Configuring /root/venv/snmpsim/data/recorded/linux-full-walk.snmprec controller
    SNMPv1/2c community name: recorded/linux-full-walk
    SNMPv3 Context Name: a172334d7d97871b72241397f713fa12 or recorded/linux-full-walk
    Configuring /root/venv/snmpsim/data/recorded/solaris-system.snmprec controller
    SNMPv1/2c community name: recorded/solaris-system
    SNMPv3 Context Name: 21dd004374d17d03e3dfa074cf39d03c or recorded/solaris-system
    Configuring /root/venv/snmpsim/data/recorded/winxp-full-walk.snmprec controller
    SNMPv1/2c community name: recorded/winxp-full-walk
    SNMPv3 Context Name: d55520dd841a3fcd0a7618889301f4ad or recorded/winxp-full-walk
    Configuring /root/venv/snmpsim/data/recorded/udp-endpoint-table-walk.snmprec controller
    SNMPv1/2c community name: recorded/udp-endpoint-table-walk
    SNMPv3 Context Name: 441ae36bd8c97e17421768a049541373 or recorded/udp-endpoint-table-walk
    Configuring /root/venv/snmpsim/data/1.3.6.1.6.1.1.0/127.0.0.1.snmprec controller
    SNMPv1/2c community name: 1.3.6.1.6.1.1.0/127.0.0.1
    SNMPv3 Context Name: b00e7c4780fffc4ca0a74e262dd116bc or 1.3.6.1.6.1.1.0/127.0.0.1
    Configuring /root/venv/snmpsim/data/hp_perf.snmprec controller
    SNMPv1/2c community name: hp_perf
    SNMPv3 Context Name: 2711b75cd6dea2b25c6d9db79dff3abd or hp_perf
    Configuring /root/venv/snmpsim/data/variation/delay.snmprec controller
    SNMPv1/2c community name: variation/delay
    SNMPv3 Context Name: 6334719eb92fc00f20e7df14ffc8f6d2 or variation/delay
    Configuring /root/venv/snmpsim/data/variation/multiplex/00007.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00007
    SNMPv3 Context Name: db2a4a17f7826b121cd6baaf830ad714 or variation/multiplex/00007
    Configuring /root/venv/snmpsim/data/variation/multiplex/00000.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00000
    SNMPv3 Context Name: 14de4d7a19be68c2a09429578218d80a or variation/multiplex/00000
    Configuring /root/venv/snmpsim/data/variation/multiplex/00004.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00004
    SNMPv3 Context Name: f816184db84e89f16bf1a3f0f798ce6e or variation/multiplex/00004
    Configuring /root/venv/snmpsim/data/variation/multiplex/00006.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00006
    SNMPv3 Context Name: 4d5ef03b64553186ccb161418552d1df or variation/multiplex/00006
    Configuring /root/venv/snmpsim/data/variation/multiplex/00002.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00002
    SNMPv3 Context Name: a98f363190bae0bb6eb215069e4e0694 or variation/multiplex/00002
    Configuring /root/venv/snmpsim/data/variation/multiplex/00008.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00008
    SNMPv3 Context Name: 2fe88e4455aa806f0e05cf234df01c89 or variation/multiplex/00008
    Configuring /root/venv/snmpsim/data/variation/multiplex/00003.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00003
    SNMPv3 Context Name: e2846ec4e4e23399ae1bea52c3cc3f25 or variation/multiplex/00003
    Configuring /root/venv/snmpsim/data/variation/multiplex/00001.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00001
    SNMPv3 Context Name: 78ed3493c53f1b7769901ad4eba77a6f or variation/multiplex/00001
    Configuring /root/venv/snmpsim/data/variation/multiplex/00009.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00009
    SNMPv3 Context Name: 6e0f5ddb1317240d8451de240210a611 or variation/multiplex/00009
    Configuring /root/venv/snmpsim/data/variation/multiplex/00010.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00010
    SNMPv3 Context Name: d9439360a67b45f63b56ef60b6245f54 or variation/multiplex/00010
    Configuring /root/venv/snmpsim/data/variation/multiplex/00005.snmprec controller
    SNMPv1/2c community name: variation/multiplex/00005
    SNMPv3 Context Name: 3b19457c6530b5c4d41a04107aed2cdc or variation/multiplex/00005
    Configuring /root/venv/snmpsim/data/variation/error.snmprec controller
    SNMPv1/2c community name: variation/error
    SNMPv3 Context Name: 83e5bd723f8095e1a27fb2b404e50404 or variation/error
    Configuring /root/venv/snmpsim/data/variation/notification.snmprec controller
    SNMPv1/2c community name: variation/notification
    SNMPv3 Context Name: fb800ce0bec7d161fcbf0249793a2b69 or variation/notification
    Configuring /root/venv/snmpsim/data/variation/sql.snmprec controller
    SNMPv1/2c community name: variation/sql
    SNMPv3 Context Name: 3fe8eeff6b172158b39f89ca150c8b0a or variation/sql
    Configuring /root/venv/snmpsim/data/variation/multiplex.snmprec controller
    SNMPv1/2c community name: variation/multiplex
    SNMPv3 Context Name: 1016117d6836664ee15b9b2af5642c3c or variation/multiplex
    Configuring /root/venv/snmpsim/data/variation/writecache.snmprec controller
    SNMPv1/2c community name: variation/writecache
    SNMPv3 Context Name: 0886e1397d572377c17c15036a1e6c66 or variation/writecache
    Configuring /root/venv/snmpsim/data/variation/subprocess.snmprec controller
    SNMPv1/2c community name: variation/subprocess
    SNMPv3 Context Name: b399244b6b33799beedc357f453a0119 or variation/subprocess
    Configuring /root/venv/snmpsim/data/variation/virtualtable.snmprec controller
    SNMPv1/2c community name: variation/virtualtable
    SNMPv3 Context Name: 329a935947144eb87ad0cdc5e08927b1 or variation/virtualtable
    Configuring /root/venv/snmpsim/data/public.snmprec controller
    SNMPv1/2c community name: public
    SNMPv3 Context Name: 4c9184f37cff01bcdc32dc486ec36961 or public
    Configuring /root/venv/snmpsim/data/cisco_16_switch.snmprec controller
    SNMPv1/2c community name: cisco_16_switch
    SNMPv3 Context Name: 906aed851a6090332cfcf762181810af or cisco_16_switch
    Configuring /root/venv/snmpsim/data/hp_perf2.snmprec controller
    SNMPv1/2c community name: hp_perf2
    SNMPv3 Context Name: c030cd1687fce01f8b29682f28f91d6d or hp_perf2
    Configuring /root/venv/snmpsim/data/mib2dev/ip-mib.snmprec controller
    SNMPv1/2c community name: mib2dev/ip-mib
    SNMPv3 Context Name: b545e61d091faca8a69f426b2bc5285d or mib2dev/ip-mib
    Configuring /root/venv/snmpsim/data/mib2dev/tcp-mib.snmprec controller
    SNMPv1/2c community name: mib2dev/tcp-mib
    SNMPv3 Context Name: ce7ca72c4091055613e6f9a22279bbcc or mib2dev/tcp-mib
    Configuring /root/venv/snmpsim/data/mib2dev/host-resources-mib.snmprec controller
    SNMPv1/2c community name: mib2dev/host-resources-mib
    SNMPv3 Context Name: e15efa7fd2910fcd23721edfe04d6f12 or mib2dev/host-resources-mib
    Configuring /root/venv/snmpsim/data/mib2dev/udp-mib.snmprec controller
    SNMPv1/2c community name: mib2dev/udp-mib
    SNMPv3 Context Name: 2193fe4afb8daee928db9dcbf9ace768 or mib2dev/udp-mib
    Configuring /root/venv/snmpsim/data/public/1.3.6.1.6.1.1.0/127.0.0.1.snmprec controller
    SNMPv1/2c community name: public/1.3.6.1.6.1.1.0/127.0.0.1
    SNMPv3 Context Name: d4c09769d12b4ec404a0a31386bd42f6 or public/1.3.6.1.6.1.1.0/127.0.0.1
    Configuring /root/venv/snmpsim/data/public/1.3.6.1.2.1.100.1.13.0.snmprec controller
    SNMPv1/2c community name: public/1.3.6.1.2.1.100.1.13.0
    SNMPv3 Context Name: 1099b06180350d8b30b977aef5a79faa or public/1.3.6.1.2.1.100.1.13.0
    Configuring /root/venv/snmpsim/data/public/1.3.6.1.2.1.100.1.2.0/__1.snmprec controller
    SNMPv1/2c community name: public/1.3.6.1.2.1.100.1.2.0/__1
    SNMPv3 Context Name: 99d7c3808c1c0725693315846b8d42ae or public/1.3.6.1.2.1.100.1.2.0/__1
    Configuring /root/venv/snmpsim/data/foreignformats/winxp1.snmpwalk controller
    SNMPv1/2c community name: foreignformats/winxp1
    SNMPv3 Context Name: 80212f5c9cbc92e175293565ef100834 or foreignformats/winxp1
    Configuring /root/venv/snmpsim/data/foreignformats/winxp2.sapwalk controller
    SNMPv1/2c community name: foreignformats/winxp2
    SNMPv3 Context Name: da761cfc8c94d3aceef4f60f049105ba or foreignformats/winxp2
    Configuring /root/venv/snmpsim/data/foreignformats/linux.snmpwalk controller
    SNMPv1/2c community name: foreignformats/linux
    SNMPv3 Context Name: bd63505107ebbd71e0046f4f30ce9c74 or foreignformats/linux
    Configuring /root/venv/snmpsim/data/bgp.snmprec controller
    SNMPv1/2c community name: bgp
    SNMPv3 Context Name: ec50a8f4d28bcb39103379379ddc5185 or bgp
  Scanning "/root/.snmpsim/data" directory for  *.snmpwalk, *.MVC, *.sapwalk, *.snmprec, *.dump data files...
  Directory "/root/.snmpsim/data" does not exist
  Scanning "/root/venv/snmpsim/data" directory for  *.snmpwalk, *.MVC, *.sapwalk, *.snmprec, *.dump data files...
    ERROR ignoring duplicate Community/ContextName "recorded/linksys-system" for data file /root/venv/snmpsim/data/recorded/linksys-system.snmprec (./snmpsim/data/recorded/linksys-system.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "recorded/linux-full-walk" for data file /root/venv/snmpsim/data/recorded/linux-full-walk.snmprec (./snmpsim/data/recorded/linux-full-walk.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "recorded/solaris-system" for data file /root/venv/snmpsim/data/recorded/solaris-system.snmprec (./snmpsim/data/recorded/solaris-system.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "recorded/winxp-full-walk" for data file /root/venv/snmpsim/data/recorded/winxp-full-walk.snmprec (./snmpsim/data/recorded/winxp-full-walk.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "recorded/udp-endpoint-table-walk" for data file /root/venv/snmpsim/data/recorded/udp-endpoint-table-walk.snmprec (./snmpsim/data/recorded/udp-endpoint-table-walk.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "1.3.6.1.6.1.1.0/127.0.0.1" for data file /root/venv/snmpsim/data/1.3.6.1.6.1.1.0/127.0.0.1.snmprec (./snmpsim/data/1.3.6.1.6.1.1.0/127.0.0.1.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "hp_perf" for data file /root/venv/snmpsim/data/hp_perf.snmprec (./snmpsim/data/hp_perf.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/delay" for data file /root/venv/snmpsim/data/variation/delay.snmprec (./snmpsim/data/variation/delay.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00007" for data file /root/venv/snmpsim/data/variation/multiplex/00007.snmprec (./snmpsim/data/variation/multiplex/00007.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00000" for data file /root/venv/snmpsim/data/variation/multiplex/00000.snmprec (./snmpsim/data/variation/multiplex/00000.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00004" for data file /root/venv/snmpsim/data/variation/multiplex/00004.snmprec (./snmpsim/data/variation/multiplex/00004.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00006" for data file /root/venv/snmpsim/data/variation/multiplex/00006.snmprec (./snmpsim/data/variation/multiplex/00006.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00002" for data file /root/venv/snmpsim/data/variation/multiplex/00002.snmprec (./snmpsim/data/variation/multiplex/00002.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00008" for data file /root/venv/snmpsim/data/variation/multiplex/00008.snmprec (./snmpsim/data/variation/multiplex/00008.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00003" for data file /root/venv/snmpsim/data/variation/multiplex/00003.snmprec (./snmpsim/data/variation/multiplex/00003.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00001" for data file /root/venv/snmpsim/data/variation/multiplex/00001.snmprec (./snmpsim/data/variation/multiplex/00001.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00009" for data file /root/venv/snmpsim/data/variation/multiplex/00009.snmprec (./snmpsim/data/variation/multiplex/00009.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00010" for data file /root/venv/snmpsim/data/variation/multiplex/00010.snmprec (./snmpsim/data/variation/multiplex/00010.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex/00005" for data file /root/venv/snmpsim/data/variation/multiplex/00005.snmprec (./snmpsim/data/variation/multiplex/00005.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/error" for data file /root/venv/snmpsim/data/variation/error.snmprec (./snmpsim/data/variation/error.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/notification" for data file /root/venv/snmpsim/data/variation/notification.snmprec (./snmpsim/data/variation/notification.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/sql" for data file /root/venv/snmpsim/data/variation/sql.snmprec (./snmpsim/data/variation/sql.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/multiplex" for data file /root/venv/snmpsim/data/variation/multiplex.snmprec (./snmpsim/data/variation/multiplex.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/writecache" for data file /root/venv/snmpsim/data/variation/writecache.snmprec (./snmpsim/data/variation/writecache.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/subprocess" for data file /root/venv/snmpsim/data/variation/subprocess.snmprec (./snmpsim/data/variation/subprocess.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "variation/virtualtable" for data file /root/venv/snmpsim/data/variation/virtualtable.snmprec (./snmpsim/data/variation/virtualtable.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "public" for data file /root/venv/snmpsim/data/public.snmprec (./snmpsim/data/public.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "cisco_16_switch" for data file /root/venv/snmpsim/data/cisco_16_switch.snmprec (./snmpsim/data/cisco_16_switch.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "hp_perf2" for data file /root/venv/snmpsim/data/hp_perf2.snmprec (./snmpsim/data/hp_perf2.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "mib2dev/ip-mib" for data file /root/venv/snmpsim/data/mib2dev/ip-mib.snmprec (./snmpsim/data/mib2dev/ip-mib.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "mib2dev/tcp-mib" for data file /root/venv/snmpsim/data/mib2dev/tcp-mib.snmprec (./snmpsim/data/mib2dev/tcp-mib.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "mib2dev/host-resources-mib" for data file /root/venv/snmpsim/data/mib2dev/host-resources-mib.snmprec (./snmpsim/data/mib2dev/host-resources-mib.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "mib2dev/udp-mib" for data file /root/venv/snmpsim/data/mib2dev/udp-mib.snmprec (./snmpsim/data/mib2dev/udp-mib.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "public/1.3.6.1.6.1.1.0/127.0.0.1" for data file /root/venv/snmpsim/data/public/1.3.6.1.6.1.1.0/127.0.0.1.snmprec (./snmpsim/data/public/1.3.6.1.6.1.1.0/127.0.0.1.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "public/1.3.6.1.2.1.100.1.13.0" for data file /root/venv/snmpsim/data/public/1.3.6.1.2.1.100.1.13.0.snmprec (./snmpsim/data/public/1.3.6.1.2.1.100.1.13.0.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "public/1.3.6.1.2.1.100.1.2.0/__1" for data file /root/venv/snmpsim/data/public/1.3.6.1.2.1.100.1.2.0/__1.snmprec (./snmpsim/data/public/1.3.6.1.2.1.100.1.2.0/__1.snmprec already loaded)
    ERROR ignoring duplicate Community/ContextName "foreignformats/winxp1" for data file /root/venv/snmpsim/data/foreignformats/winxp1.snmpwalk (./snmpsim/data/foreignformats/winxp1.snmpwalk already loaded)
    ERROR ignoring duplicate Community/ContextName "foreignformats/winxp2" for data file /root/venv/snmpsim/data/foreignformats/winxp2.sapwalk (./snmpsim/data/foreignformats/winxp2.sapwalk already loaded)
    ERROR ignoring duplicate Community/ContextName "foreignformats/linux" for data file /root/venv/snmpsim/data/foreignformats/linux.snmpwalk (./snmpsim/data/foreignformats/linux.snmpwalk already loaded)
    ERROR ignoring duplicate Community/ContextName "bgp" for data file /root/venv/snmpsim/data/bgp.snmprec (./snmpsim/data/bgp.snmprec already loaded)
  Scanning "/root/venv/share/snmpsim/data" directory for  *.snmpwalk, *.MVC, *.sapwalk, *.snmprec, *.dump data files...
  Directory "/root/venv/share/snmpsim/data" does not exist
  Scanning "/root/venv/lib/python2.7/site-packages/snmpsim/data" directory for  *.snmpwalk, *.MVC, *.sapwalk, *.snmprec, *.dump data files...
  Directory "/root/venv/lib/python2.7/site-packages/snmpsim/data" does not exist
  --- SNMPv3 USM configuration
  SNMPv3 USM SecurityName: simulator
  SNMPv3 USM authentication key: auctoritas, authentication protocol: MD5
  SNMPv3 USM encryption (privacy) key: privatus, encryption protocol: DES
  Maximum number of variable bindings in SNMP response: 64
  --- Transport configuration
  Listening at UDP/IPv4 endpoint 127.0.0.1:1024, transport ID 1.3.6.1.6.1.1.0
 Above is the output when I start up snmpsimd

**Comment by etingof** [comment]
I do the same steps on Linux and it works for me. I suspect it has something to do with vent and root. Could you do the same, but under a non-root user?

**Comment by kmart5678** [comment]
Yes! that did it. I'm really appreciate that you responded so fast also. Thanks again!
