### ISSUE TITLE
variation-module-options not picking up custom notifications

### ISSUE THREAD

**Issue by HoneyryderChuck** [etingof/snmpsim#8]
I'm setting up my own notifications.snmprec locally, and want to start the simulator with it. For that I use the `--variation-module-options` cli option:

```bash
> snmpsimd.py ... --variation-module-options=file:./test/custom/notifications.snmprec
```

For testing purposes, I'm only using v1, which notifies on `sysDescr.0` get request. I've replaced all instances of localhost ip address to all:

```
# in the original, 0.0.0.0 is 127.0.0.1

1.3.6.1.2.1.1.1.0|4:notification|op=get,version=1,community=public,proto=udp,host=0.0.0.0,port=162,ntftype=trap,trapoid=1.3.6.1.4.1.20408.4.1.1.2.0.432,uptime=12345,agentaddress=0.0.0.0,enterprise=1.3.6.1.4.1.20408.4.1.1.2,varbinds=1.3.6.1.2.1.1.1.0:s:snmpsim agent:1.3.6.1.2.1.1.3.0:i:42,value=SNMPv1 trap sender
```

However, I'm not seeing the simulator picking up the variation module. Nothing in the boot log shows me that. Neither does the notification log, when I send the aforementioned get request:

```
generateRequestMsg: Message:
 version=0
 community=public
 data=PDUs:
  trap=TrapPDU:
   enterprise=1.3.6.1.4.1.20408.4.1.1.2
   agent-addr=NetworkAddress:
    internet=127.0.0.1

   generic-trap='enterpriseSpecific'
   specific-trap=432
   time-stamp=12345
   variable-bindings=VarBindList:
    VarBind:
     name=1.3.6.1.2.1.1.1.0
     value=ObjectSyntax:
      simple=SimpleSyntax:
       string=snmpsim agent


sendPdu: MP succeeded
sendMessage: outgoingMessage queued (75 octets) 
00000: 30 49 02 01 00 04 06 70 75 62 6C 69 63 A4 3C 06 
00016: 0C 2B 06 01 04 01 81 9F 38 04 01 01 02 40 04 7F 
00032: 00 00 01 02 01 06 02 02 01 B0 43 02 30 39 30 1B 
00048: 30 19 06 08 2B 06 01 02 01 01 01 00 04 0D 73 6E 
00064: 6D 70 73 69 6D 20 61 67 65 6E 74
sendPdu: message sent
sendVarBinds: notificationHandle 1248347119, sendRequestHandle None, timeout 100
sendVarBinds: notificationHandle 1248347119, sendRequestHandle None, notification(s) sent
notification: sending Notification to CommunityData(communityIndex='s-89801506981894444', communityName=<COMMUNITY>, mpModel=0, contextEngineId=None, contextName='', tag='7195984095063770675', s
'7195984095063770675')
Response var-binds: 1.3.6.1.2.1.1.1.0=<SNMPv1 trap sender>
sendVarBinds: stateReference 1246831, errorStatus 0, errorIndex 0, varBinds [(ObjectIdentifier('1.3.6.1.2.1.1.1.0'), OctetString('SNMPv1 trap sender'))]
v2ToV1: v2Pdu ResponsePDU:
 request-id=15477247
 error-status='noError'
 error-index=0
 variable-bindings=VarBindList:
  VarBind:
   name=1.3.6.1.2.1.1.1.0
   =_BindValue:
    value=ObjectSyntax:
     simple=SimpleSyntax:
      string-value=SNMPv1 trap sender
```

I still see `127.0.0.1`, so I conclude that the option was ignored.

Is this a bug or a wrong usage of the platform?

Just as a note on why this is important for me: I'm running the simulator in a docker container for isolation. I want to expose port 162 of the container and listen there for the notifications, so the snmpsim has to be sending the notifications to 0.0.0.0 interface.

**Comment by etingof** [comment]
Thank you for rising this issue!

Though I'm not certain why you are using the `--variation-module-options=` here. If I understand your goal correctly, I'd probably put your version of `notifications.snmprec` into a directory (let's say it's `~/data`), then point `snmpsimd` to it like this:

```
$ snmpsimd.py --data-dir=~/data --agent-udpv4-endpoint=127.0.0.1:161
```

Then send SNMPv1 `GET 1.3.6.1.2.1.1.1.0` towards `127.0.0.1:161` with community name `notifications` (which is the name of your .snmprec file) so simulator should pick it up then.

Does it make sense?

You may also need to point `snmpsimd` to your variation modules collection via `--variation-modules-dir=` option.


 --variation-modules-dir=

**Comment by HoneyryderChuck** [comment]
> does it make sense?

yes, and no :=) As they are, I'm using the default data from the simulator in my specs. Won't setting the data-dir parameter override that default dir you are already using? That'd be a bit of a no-go if it would. I want to "extend" a community (at worst add a new one), not delete the others.

I also see that community has to be specifically referenced. At some point I might have to do the same for v3, will I be able to reuse these files? How should I signal them for a specific engine/user ( I see something already in the default file, but not sure how that maps) ?

**Comment by etingof** [comment]
> Won't setting the data-dir parameter override that default dir you are already using?

There is the [default](https://github.com/etingof/snmpsim/blob/master/snmpsim/confdir.py#L47) data files search list in which `--data-dir` would be  added in front of the default ones ([unless](https://github.com/etingof/snmpsim/blob/master/scripts/snmpsimd.py#L628) you configure many SNMP engines).

> I also see that community has to be specifically referenced. 

Well, there is usually some community name when in comes to SNMP v1/v2c. The universally used one is 'public' so you may consider [symlinking](http://snmpsim.sourceforge.net/sharing-snapshots.html)  *public.snmprec -> variation/notification.snmprec* and/or *1.3.6.1.6.1.1.0.snmprec -> public.snmprec* to reuse them across different simulated agents. In the latter case you could probably use empty community name.

With SNMPv3 there is `context-name` to identify simulated agent so it also maps to .snmprec files.. The `context-name` could be empty.

> How should I signal them for a specific engine/user

SNMPv3 users do not take part in .snmprec file selection, just SNMPv3 `context-name`.

**Comment by HoneyryderChuck** [comment]
> There is the default data files search list in which --data-dir would be added in front of the default ones (unless you configure many SNMP engines).

I am configuring snmp engines, and using  `--data-dir` is overwriting everything, so it's a no-option.

However, I worked around this by mounting my `.snmprec` into one of those locations from the link you sent, namely the home's `.snmpsim` (thx for the tip, btw), and I'm now finally reaching my custom community. 


I'm having now a different issue. docker for Mac OS (my OS) is rather limited, and [makes it very hard for a containerized software to communicate with the host](https://docs.docker.com/docker-for-mac/networking/#there-is-no-docker0-bridge-on-macos) (search for `I WANT TO CONNECT FROM A CONTAINER TO A SERVICE ON THE HOST` paragraph). 

The simulator log shows that the notification traps are sent to `0.0.0.0` address:

```
Request var-binds: 1.3.6.1.2.1.1.1.0=<>, flags: EXACT, GET
# this bind right here!
notification: binding to local address 0.0.0.0
notification: sending Notification to CommunityData(communityIndex='s-2260580198466038060', communityName=<COMMUNITY>, mpModel=0, contextEngineId=None, contextName='', tag='4959588516569414953', securityName='s-2260580198466038060') with credentials UdpTransportTarget(('10.200.10.1', 162), timeout=1, retries=5, tagList='4959588516569414953')
```

according to the link I sent, the service would have to bind directly to the IP I will alias the loopback interface to. But I don't know if it's possible to change that `0.0.0.0` (I'd expect it to broadcast to all available interfaces, sadly I don't see it happening).

What I'm doing on the host machine: 

```
> nc -u -l 10.200.10.1 $#{exposed-port-162-from-container}
```

If it all works, I should see some output (the encoded trap PDU). 

Hopefully you could help me with that, although not everyone has been playing with snmp and containers.

**Comment by HoneyryderChuck** [comment]
I've also tried to arbitrarily send an udp packet to the host machine, and I've just confirmed:

```
# from container bash
> echo -n "hello" > /dev/udp/10.200.10.1/${hostmachineport} #=> I see the hello
> echo -n "hello" > /dev/udp/0.0.0.0/${hostmachineport} #=> I don't see the hello
```

So I confirm, I really need to set that trap IP. Hopefully you can help to find out how.

**Comment by etingof** [comment]
I think you can do either of two things:

1. Add `bindaddr=10.200.10.1` option to your `notification.snmprec`
2. Bind snmpsimd itself to the alias IP (10.200.10.1). This will have a side effect of trap sender (inside notification variation module) binding to the same IP when sending traps (e.g. TRAP will come from 10.200.10.1).

Here's the relevant [piece of code](https://github.com/etingof/snmpsim/blob/master/variation/notification.py#L168) responsible for the above behavior.

**Comment by HoneyryderChuck** [comment]
I was hoping more to set the IP as a parameter, as this is rarely static in a docker container setup. Nevertheless, I can still get it beforehand and generate the snmprec based on it in plain bash.

Thx again!
