### ISSUE TITLE
Table view not working in MIB browsers

### ISSUE THREAD

**Issue by FLamorce** [etingof/snmpsim#81]
I have a simple rec file for a Cisco UCS, MIB is CISCO-UNIFIED-COMPUTING-EQUIMET-MIB, you can contact me if you want the full MIBs and rec.

1.3.6.1.2.1.1.5|4x|30
1.3.6.1.4.1.9.9.719.1.15.56.1.1.1|65|1
1.3.6.1.4.1.9.9.719.1.15.56.1.1.2|65|2
1.3.6.1.4.1.9.9.719.1.15.56.1.3.1|4x|30
1.3.6.1.4.1.9.9.719.1.15.56.1.3.2|4x|30
1.3.6.1.4.1.9.9.719.1.15.56.1.6.1|4x|30
1.3.6.1.4.1.9.9.719.1.15.56.1.6.2|4x|30

1.3.6.1.4.1.9.9.719.1.15.56 is a table, 1.3.6.1.4.1.9.9.719.1.15.56.1 is an entry, and the subsequent .1 and .2 are for 2 rows. However while in iReasoning, "Table View" does not work, it returns an empty table. Also if I emulate the device with SAPro for instance, I can double click in iReasoning on any element in the table and it would give me the different valu for each index, but not with snmpsim. Is this something I do wrong with table in my snmprec?

**Comment by etingof** [comment]
One thing I noticed is that you have value type ([65](http://snmplabs.com/snmpsim/managing-simulation-data.html#file-format)), which is Counter32, while in the [CISCO-UNIFIED-COMPUTING-MIB](http://mibs.snmplabs.com/asn1/CISCO-UNIFIED-COMPUTING-MIB) the value type seems to be `Unsigned32`:

```
CucsManagedObjectId ::= TEXTUAL-CONVENTION
        DISPLAY-HINT "d"
        STATUS current
        SYNTAX         Unsigned32
```

How did you make this .snmprec file? If you did that by hand, there are many [semi-automatic ways](http://snmplabs.com/snmpsim/building-simulation-data.html) to build one.

A good way to debug such problem I think would be to `snmpwalk` snmpsim, SAPro or whatever other source works for you and compare the outcome. There are some [command-line options](http://snmplabs.com/snmpclitools/snmpwalk.html#snmpwalk-options-output) that reveal more details on the SNMP message.

**Comment by FLamorce** [comment]
I did it by hand, I tried others value for the type, it changes nothing, I cannot use "table view" :-/
I will try to generate value for the MIB and see what it output and how it reacts when doing a table view

**Comment by etingof** [comment]
Can you try `snmpwalk` to see what's the difference in response when you do it against different agents?

Also, what's in snmpsimd log when you try to browse that table? If you could share a snippet, that would be helpful.
