### ISSUE TITLE
Permission issue with cache file running as root

### ISSUE THREAD

**Issue by timlegge** [etingof/snmpsim#84]
Hi
I am running as root to use port 161 as:

`sudo snmpsimd.py --process-user=me --process-group=me --agent-udpv4-endpoint=192.168.122.244:161 --data-dir=/home/me/.snmpsimd/data --cache-dir=/home/me/.snmpsim/cache`

I do a snmpwalk to test:
```
snmpwalk 192.168.122.244 -v 1 -c apc-full .1.3.6.1.4.1.318
End of MIB
```

snmpsimd outputs:
```
Unsupported index format, rebuilding index /home/me/.snmpsim/cache/_home_me_.snmpsim_data_apc-full.dbm
ERROR Problem with data file or its index: Failed to create /home/me/.snmpsim/cache/_home_me_.snmpsim_data_apc-full.dbm for data file /home/me/.snmpsim/data/apc-full.snmprec: None 
```

To work around:

`sudo chown me:me .snmpsim/cache/_home_me_.snmpsim_data_apc-full.dbm `

**Comment by etingof** [comment]
You may want to try code from master - there is a [relevant fix](https://github.com/etingof/snmpsim/blob/master/CHANGES.txt#L16) there.

**Comment by timlegge** [comment]
I know this has been a while but I still have this issue.  In fact I even created a docker container to install from a git clone and I see the exact same issue.  It is only resolved by chown to the snmpsim user after the cache is created.
From what I can tell the problem is that while the fix does create the directory with the appropriate owner if it does not exist the cache files that are created  are all created with the root user as the owner
I would expect that what ever creates the files needs to also have the fix or more likely the script should drop its privileges immediate after the cache directory is created and the port is opened for listening.

**Comment by timlegge** [comment]
Works for me
