### ISSUE TITLE
Community string "public" still works though another was set

### ISSUE THREAD

**Issue by amitpprat** [etingof/snmpsim#85]
Hello,
When I ran the simulator with a data dir containing   .snmprec file, named 1500 for instance, both "1500" and "public" work in snmpget as community strings.
But "public" should not be a valid community string once I set "1500" , right?

**Comment by etingof** [comment]
Right, 'public' not not in any way special so it should not be available it the .snmprec file is not there.

Can you share snmpsimd log showing daemon startup and request handling?

**Comment by amitpprat** [comment]
I found the problem, it found default .snmprec files installed with snmpsimd. Thanks.
