### ISSUE TITLE
Unable to convert snmpwalk from Fortigate

### ISSUE THREAD

**Issue by polaris197** [etingof/snmpsim#87]
The SnmpWalk import failed to parse the "clear(1)" string

.1.3.6.1.4.1.12356.101.14.4.1.1.3.1.xx.xx.xx.xx.xx.xx.xx.xx.xx.xx.xx.xx.xx.xx.xx = BITS: 40 clear(1)

Solution:
snmpsim/snmpsim/grammar/walk.py line  85
replace by:
match = re.match(r'^([0-9a-fA-F]{2}(\s+[0-9a-fA-F]{2})*)', value)

**Comment by etingof** [comment]
Thanks for reporting this!

The fastest way to get it fixed is to push a PR. ;-)

**Comment by etingof** [comment]
BTW, @landy2005 may have looked into that or somehow relevant code lately...

**Comment by polaris197** [comment]
Sorry, i can't create a PR

Can't connect to any URI: https://github.com/etingof/snmpsim.git (https://github.com/etingof/snmpsim.git: git-receive-pack not permitted on 

Here the patch 

diff --git a/snmpsim/grammar/walk.py b/snmpsim/grammar/walk.py
index 66f67ff..3d5bb92 100644
--- a/snmpsim/grammar/walk.py
+++ b/snmpsim/grammar/walk.py
@@ -81,8 +81,9 @@
     def _bitsFilter(value):
         # rfc1902.Bits does not really initialize from sequences
         # Clean bits values
-        # .1.3.6.1.2.1.17.6.1.1.1.0 = BITS: 5B 00 00 00   [[...]1 3 4 6 7
-        match = re.match(r'^([0-9a-fA-F]{2}(\s+[0-9a-fA-F]{2})*)\s+\[', value)
+        # .1.3.6.1.2.1.17.6.1.1.1.0 = BITS: 5B 00 00 00   [[...]1 3 4 6 7        
+        # .1.3.6.1.2.1.17.6.1.1.1.0 = BITS: 5B 00 00 00   clear(1)        
+        match = re.match(r'^([0-9a-fA-F]{2}(\s+[0-9a-fA-F]{2})*)', value)
         if match:
             return ints2octs([int(y, 16) for y in match.group(1).split(' ')])

**Comment by etingof** [comment]
Here is the patch that I've pushed to master:

```
-        match = re.match(r'^([0-9a-fA-F]{2}(\s+[0-9a-fA-F]{2})*)\s+\[', value)
+        match = re.match(r'^([0-9a-fA-F]{2}(\s+[0-9a-fA-F]{2})*)', value)
```

I hope it does not break anything else. 

Thanks!

**Comment by polaris197** [comment]
I don't think
This regex match only valib bits

Thanks a lot

Le lun. 2 sept. 2019 à 10:55, Ilya Etingof <notifications@github.com> a
écrit :

**Comment by landy2005** [comment]
> Here is the patch that I've pushed to master:
> 
> ```
> -        match = re.match(r'^([0-9a-fA-F]{2}(\s+[0-9a-fA-F]{2})*)\s+\[', value)
> +        match = re.match(r'^([0-9a-fA-F]{2}(\s+[0-9a-fA-F]{2})*)', value)
> ```
> 
> I hope it does not break anything else.

Probably should work correctly, my original bits "test" string written in code comment:
```
.1.3.6.1.2.1.17.6.1.1.1.0 = BITS: 5B 00 00 00   [[...]1 3 4 6 7
```
