### ISSUE TITLE
Incorrect getnext Oid when partial snmprec used

### ISSUE THREAD

**Issue by landy2005** [etingof/snmpsim#90]
I have such unifi-1.snmprec file, with content:
```
1.3.6.1.2.1.1.1.0|4|Linux 3.3.8 #1 Wed Jan 18 09:26:53 PST 2017 mips
1.3.6.1.2.1.1.2.0|6|1.3.6.1.4.1.10002.1
1.2.840.10036.3.1.2.1.3.6|4|UAP
```

when I requested some specific Oid by getnext:
```
snmpgetnext -v2c -c 'unifi-1' -Pud -OQUv -m IEEE802dot11-MIB -M /opt/observium/mibs/rfc:/opt/observium/mibs/net-snmp 'udp':'127.0.0.1':'16111' dot11manufacturerProductName
```
I get result as `"Linux 3.3.8 #1 Wed Jan 18 09:26:53 PST 2017 mips"`, which matches to first line in snmprec file.

But correct answer should be `"UAP"`, because
```
$ snmptranslate -On IEEE802dot11-MIB::dot11manufacturerProductName
.1.2.840.10036.3.1.2.1.3
```

(Oid correctly translated to numeric oid by net-snmp cmd, same incorrect result will be with numeric oid query:
`snmpgetnext -v2c -c <community> <hostname> .1.2.840.10036.3.1.2.1.3`

Logically snmpsimd should return `1.2.840.10036.3.1.2.1.3.6` in that case.

**Comment by etingof** [comment]
Sorry for delayed response!

I think the problem here might be in the ordering of the OIDs in your .snmprec file - the OIDs should always be incrementally ordered, otherwise GETNEXT would behave funnily.

**Comment by landy2005** [comment]
oh, dear.. I completely forgot about sorting.
You're right, this fixed this problem :D

**Comment by etingof** [comment]
BTW, `datafile` tool can be used to ensure .snmprec sorting.
