### ISSUE TITLE
Override default data/variation directories

### ISSUE THREAD

**Issue by timlegge** [etingof/snmpsim#93]
Hi

I am putting together a docker container aimed at specific testing of a dcim tool and I would like to have snmpsim ignore the delivered snmp data that is delivered with the project in favour of the data a data set that the container provides or the user overrides.

I would expect that --data-dir would override the packaged files but if that is not the desired behavior how about a option --no-search-data or something similar:

**Comment by etingof** [comment]
I am not sure I understood your concern here... I think if you are using `--data-dir` (and `--variation-modules-dir`), those options should override all defaults.

Perhaps it makes perfect sense to me to ignore shipped simulation data if you have your own.

**Comment by timlegge** [comment]
When I start up with my --data-dir I expect it to only search and index
that directory.

However it seems to process and index a lot of default directories
/root/snmpsim etc...

For my purposes I would like to avoid that as I want to ensure a known
testing state.

Tim

**Comment by etingof** [comment]
Right, I see. One of the possibilities to overcome this would be to explicitly specify `--v3-engine-id`. If you do that, then you create a distinct SNMP engine instance with all of the following options bound to it. In this mode, all the defaults would be overridden.

Not obvious, indeed. I will document that.

Does it make sense so far?

**Comment by timlegge** [comment]
Makes sense and it tests fine.
